import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs';
import "./globals.css";
import { ukUA } from '@clerk/localizations'

import Topbar from "../components/TopBar";
import Footer from "../components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider localization={ukUA}>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased pt-16`}
        >
          <Topbar />

          <div className="layout-container">
            {children}
          </div>

          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
